name: Feature request
description: Suggest an improvement for mac-motd
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain point are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
